declare module '@bit/mcmanus68.ui-react.section'
declare module '@bit/mcmanus68.ui-react.section-headline'
declare module '@bit/mcmanus68.ui-react.section-hero'
declare module '@bit/mcmanus68.ui-react.block-image-gallery'
declare module '@bit/mcmanus68.ui-react.block-simple-content'
declare module '@bit/mcmanus68.ui-react.footer-simple-content'
declare module '@bit/mcmanus68.ui-react.footer-social'
declare module '@bit/mcmanus68.ui-react.footer-newsletter'
declare module '@bit/mcmanus68.ui-react.back-to-top'

declare module 'react-reveal/*'
declare module 'react-bootstrap'
declare module 'redux'
